import type { Metadata } from "next";
import {  Anek_Latin } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";

const aneklatin = Anek_Latin({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aneklatin.className} min-h-screen flex flex-col antialiased`}
      >
        <div className="flex-1 h-full">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
